services:
  backend:
    build: ./backend
    # Docker va lire la dockerfile dans backend/
    container_name: backend
    # nom du conteneur
    ports:
      - "3000:3000"
      - "5555:5555"
      # le backend est accessible sur le port localhost:3000
    volumes:
      - ./backend/src:/backend/src
      # Quand on modifiera le code, docker le verra et reloadera.
      - ./backend/prisma:/backend/prisma

    depends_on:
      db:
        condition: service_healthy
      # Le backend démarre après la base de données mySQL
    env_file:
      - ./backend/.env
      # Le backend se connecte à MySQL via le nom du service Docker : db + charge le .env
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/villageByCa:/frontend/villageByCa
      - /frontend/villageByCa/node_modules


    depends_on:
      - backend
      # Le frontend se lance après le backend

  db:
    image: mysql:8
    # Utilises l’image officielle de mySQL 8
    container_name: mysql
    restart: always
    # MySQL plante (ça arrive) Docker le relance immédiatement.
    env_file:
      - .env

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Sauvegarde persistante des données MySQL, même si le conteneur est supprimé
      # Vérifie que le service mysql est prêt à être utilisé, docker le ping jusqu'à avoir un résultat positif
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql-backup:
    image: mysql:8
    container_name: mysql-backup
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backups:/backups
    # Lance un script qui tourne en permanence, et exporte avec mysqldump la DB
    # On les met dans un fichier compressé par gzip dans le dossier backups
    # On supprime les fichiers de plus de 30 jours
    # On attend ensuite 1 semaine avant de refaire une sauvegarde
    entrypoint: >
      sh -c "
        while true; do
          echo '[Backup] Dump started at ' $(date);
          mysqldump -h db -u root -p\"$$MYSQL_ROOT_PASSWORD\" \"$$MYSQL_DATABASE\" | gzip > /backups/db_$(date +%F_%H-%M-%S).sql.gz;
          if [ $$? -eq 0 ]; then
            echo '[Backup] Dump finished successfully';
          else
            echo '[Backup] Dump FAILED';
          fi;
          find /backups -type f -mtime +30 -delete;
          sleep 604800;
        done
      "



volumes:
  mysql_data:
  # Crée un volume nommé mysql_data sur notre machine (on stocke les données de la database sur notre machine en phase de développement.
